<a href="https://colab.research.google.com/github/partho1999/sentiment_analysis-with-reviews-feedback-data-and-social-media-scrape--data/blob/main/covid_19_text_sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Google

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/google.csv')

In [ ]:
df.shape

(79, 7)

In [ ]:
df.columns

Index(['date', 'title', 'media', 'datetime', 'desc', 'link', 'img'], dtype='object')

In [ ]:
df.head()

             date  ...                                                img
0     5 hours ago  ...  https://lh3.googleusercontent.com/proxy/0q2iCd...
1  29 minutes ago  ...  https://lh3.googleusercontent.com/proxy/u08Qn9...
2    10 hours ago  ...  https://lh3.googleusercontent.com/proxy/KaNMEW...
3     3 hours ago  ...  https://lh3.googleusercontent.com/proxy/gcqbZ8...
4    11 hours ago  ...  https://lh3.googleusercontent.com/proxy/-WOGvE...

[5 rows x 7 columns]

In [ ]:
import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
corpus=[]

for i in range(0, 79):
  title = re.sub('(@[A-Za-z0-9]+)|(#[A-Za-z0-9]+)|([^0-9A-Za-z t])|(w+://S+)', ' ', df['title'][i])
  title = title.split("https")[0]
  title = title.lower()
  title = title.split()
  title = [ps.stem(word) for word in title if not word in set(all_stopwords)]
  title = ' '.join(title)
  corpus.append(title)

In [ ]:
df['Text'] = corpus
df.head()

             date  ...                                              Text
0     5 hours ago  ...    covid 19 case student faculti decreas slightli
1  29 minutes ago  ...  covid 19 case mask mandat vaccin news live updat
2    10 hours ago  ...       covid 19 pandem utah move emerg endem phase
3     3 hours ago  ...     oha report 1k new covid 19 case declin hospit
4    11 hours ago  ...                covid 19 death 2 772 hospit steadi

[5 rows x 8 columns]

In [ ]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [ ]:
sid = SentimentIntensityAnalyzer()

In [ ]:
df['scores'] = df['Text'].apply(lambda Text: sid.polarity_scores(Text))
df.head()

             date  ...                                             scores
0     5 hours ago  ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
1  29 minutes ago  ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
2    10 hours ago  ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
3     3 hours ago  ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
4    11 hours ago  ...  {'neg': 0.438, 'neu': 0.562, 'pos': 0.0, 'comp...

[5 rows x 9 columns]

In [ ]:
 df[['title','scores']]

                                                title                                             scores
0   COVID-19 cases in students and faculty decreas...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
1   Covid-19 Cases, Mask Mandates and Vaccine News...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
2   Is the COVID-19 pandemic over? Utah moving fro...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
3   OHA reports over 1K new COVID-19 cases, declin...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
4   COVID-19 deaths up to 2,772; Hospitalizations ...  {'neg': 0.438, 'neu': 0.562, 'pos': 0.0, 'comp...
..                                                ...                                                ...
74  Daily briefing: Why COVID-19 reinfections are ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
75  Portugal drops most COVID-19 rules as Omicron ...  {'neg': 0.259, 'neu': 0.741, 'pos': 0.0, 'comp...
76  Missouri plotting official 'end' to COVID-19 p...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
77  COVID-19 reporting data moves to Iowa Dept. of...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
78  The COVID-19 Global Action Meeting - United St...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...

[79 rows x 2 columns]

In [ ]:
df = pd.concat([df, df['scores'].apply(pd.Series)], axis=1)

In [ ]:
df[['title','neg', 'neu', 'pos', 'compound']]

                                                title    neg  ...  pos  compound
0   COVID-19 cases in students and faculty decreas...  0.000  ...  0.0    0.0000
1   Covid-19 Cases, Mask Mandates and Vaccine News...  0.000  ...  0.0    0.0000
2   Is the COVID-19 pandemic over? Utah moving fro...  0.000  ...  0.0    0.0000
3   OHA reports over 1K new COVID-19 cases, declin...  0.000  ...  0.0    0.0000
4   COVID-19 deaths up to 2,772; Hospitalizations ...  0.438  ...  0.0   -0.5994
..                                                ...    ...  ...  ...       ...
74  Daily briefing: Why COVID-19 reinfections are ...  0.000  ...  0.0    0.0000
75  Portugal drops most COVID-19 rules as Omicron ...  0.259  ...  0.0   -0.2732
76  Missouri plotting official 'end' to COVID-19 p...  0.000  ...  0.0    0.0000
77  COVID-19 reporting data moves to Iowa Dept. of...  0.000  ...  0.0    0.0000
78  The COVID-19 Global Action Meeting - United St...  0.000  ...  0.0    0.0000

[79 rows x 5 columns]

Twitter

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/twitter.csv')

In [ ]:
df.columns

Index(['date', 'user', 'name', 'text', 'retweet', 'favorite', 'location'], dtype='object')

In [ ]:
df.shape

(500, 7)

In [ ]:
df.head()

                        date           user  ... favorite                  location
0  2022-02-19 05:49:56+00:00   ExportGenius  ...        0   New Delhi, India 110085
1  2022-02-19 05:49:41+00:00    AndyVermaut  ...        0         Diksmuide, België
2  2022-02-19 05:49:39+00:00   ayungonnegor  ...        0  Ayungon, Negros Oriental
3  2022-02-19 05:49:39+00:00      auscandoc  ...        0                       NaN
4  2022-02-19 05:49:35+00:00  get_it_maggie  ...        0            East Tennessee

[5 rows x 7 columns]

In [ ]:
import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
corpus=[]

for i in range(0, 500):
  text = re.sub('(@[A-Za-z0-9]+)|(#[A-Za-z0-9]+)|([^0-9A-Za-z t])|(w+://S+)', ' ', df['text'][i])
  text = text.split("https")[0]
  text = text.lower()
  text = text.split()
  text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
  text = ' '.join(text)
  corpus.append(text)

In [ ]:
df['Text'] = corpus
df.head()

                        date  ...                                               Text
0  2022-02-19 05:49:56+00:00  ...  pharmaceut industri saw tremend growth global ...
1  2022-02-19 05:49:41+00:00  ...  andi vermaut share live china brief covid 19 c...
2  2022-02-19 05:49:39+00:00  ...  ayungon launch resbakuna kid today 20 children...
3  2022-02-19 05:49:39+00:00  ...  jama network famili member icu patient ptsd re...
4  2022-02-19 05:49:35+00:00  ...  tn bother not like go attack one hub much like...

[5 rows x 8 columns]

In [ ]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [ ]:
sid = SentimentIntensityAnalyzer()

In [ ]:
df['scores'] = df['Text'].apply(lambda Text: sid.polarity_scores(Text))
df.head()

                        date  ...                                             scores
0  2022-02-19 05:49:56+00:00  ...  {'neg': 0.0, 'neu': 0.809, 'pos': 0.191, 'comp...
1  2022-02-19 05:49:41+00:00  ...  {'neg': 0.0, 'neu': 0.804, 'pos': 0.196, 'comp...
2  2022-02-19 05:49:39+00:00  ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
3  2022-02-19 05:49:39+00:00  ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
4  2022-02-19 05:49:35+00:00  ...  {'neg': 0.385, 'neu': 0.466, 'pos': 0.149, 'co...

[5 rows x 9 columns]

In [ ]:
 df[['text','scores']]

                                                  text                                             scores
0    The pharmaceutical industry saw tremendous gro...  {'neg': 0.0, 'neu': 0.809, 'pos': 0.191, 'comp...
1    Andy Vermaut shares:Live: China briefs on COVI...  {'neg': 0.0, 'neu': 0.804, 'pos': 0.196, 'comp...
2    JUST IN: Ayungon launches its RESBAKUNA KIDS t...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
3    JAMA Network “family members of ICU patients, ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
4    @laidbackntx TN, same, but why bother? Not lik...  {'neg': 0.385, 'neu': 0.466, 'pos': 0.149, 'co...
..                                                 ...                                                ...
495  @PointsLaughs You go cherry picking snippets o...  {'neg': 0.256, 'neu': 0.744, 'pos': 0.0, 'comp...
496  #Thread |\n1st case of #Deltacron variant of C...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
497  @greenmtpics “Conclusions.... In this randomiz...  {'neg': 0.189, 'neu': 0.811, 'pos': 0.0, 'comp...
498  Watching protestors partying in Wellington on ...  {'neg': 0.241, 'neu': 0.759, 'pos': 0.0, 'comp...
499  @DrJBhattacharya "Justin Trudeau should have f...  {'neg': 0.0, 'neu': 0.813, 'pos': 0.187, 'comp...

[500 rows x 2 columns]

In [ ]:
df = pd.concat([df, df['scores'].apply(pd.Series)], axis=1)

In [ ]:
df[['text','neg', 'neu', 'pos', 'compound']]

                                                  text    neg  ...    pos  compound
0    The pharmaceutical industry saw tremendous gro...  0.000  ...  0.191    0.3818
1    Andy Vermaut shares:Live: China briefs on COVI...  0.000  ...  0.196    0.2960
2    JUST IN: Ayungon launches its RESBAKUNA KIDS t...  0.000  ...  0.000    0.0000
3    JAMA Network “family members of ICU patients, ...  0.000  ...  0.000    0.0000
4    @laidbackntx TN, same, but why bother? Not lik...  0.385  ...  0.149   -0.4707
..                                                 ...    ...  ...    ...       ...
495  @PointsLaughs You go cherry picking snippets o...  0.256  ...  0.000   -0.4767
496  #Thread |\n1st case of #Deltacron variant of C...  0.000  ...  0.000    0.0000
497  @greenmtpics “Conclusions.... In this randomiz...  0.189  ...  0.000   -0.2732
498  Watching protestors partying in Wellington on ...  0.241  ...  0.000   -0.5859
499  @DrJBhattacharya "Justin Trudeau should have f...  0.000  ...  0.187    0.3182

[500 rows x 5 columns]

Facebook

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/Facebook_post.csv')

In [ ]:
df.columns

Index(['Name', 'Time', 'Post'], dtype='object')

In [ ]:
df.shape[0]

38

In [ ]:
df.head()

,Name,Time,Post
0,CGTN,China state-controlled media,A new Perspective in Science discusses the neu...
1,CGTN,China state-controlled media,Millions of high-risk Americans are dealing wi...
2,CGTN,China state-controlled media,"করোনায় মৃত্যু বেড়ে ৩৪, বাড়ল শনাক্তও #covid19 #..."
3,"See all public posts for ""covid-19""",9 February at 20:20,Judy Ann Santos is extremely elated that her s...
4,Science,China state-controlled media,Feel like you're juggling more work than ever?...

In [ ]:
import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
corpus=[]

for i in range(0, df.shape[0]):
  post = re.sub('(@[A-Za-z0-9]+)|(#[A-Za-z0-9]+)|([^0-9A-Za-z t])|(w+://S+)', ' ', df['Post'][i])
  post = post.split("https")[0]
  post = post.lower()
  post = post.split()
  post = [ps.stem(word) for word in post if not word in set(all_stopwords)]
  post = ' '.join(post)
  corpus.append(post)

In [ ]:
df['post'] = corpus
df.head()

,Name,Time,Post,post
0,CGTN,China state-controlled media,A new Perspective in Science discusses the neu...,new perspect scienc discuss neurolog symptom a...
1,CGTN,China state-controlled media,Millions of high-risk Americans are dealing wi...,million high risk american deal strain grief n...
2,CGTN,China state-controlled media,"করোনায় মৃত্যু বেড়ে ৩৪, বাড়ল শনাক্তও #covid19 #...",translationprothomalo com visit covid 19 infor...
3,"See all public posts for ""covid-19""",9 February at 20:20,Judy Ann Santos is extremely elated that her s...,judi ann santo extrem elat six year old daught...
4,Science,China state-controlled media,Feel like you're juggling more work than ever?...,feel like juggl work ever not alon two third w...

In [ ]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

/usr/local/lib/python3.7/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "

In [ ]:
sid = SentimentIntensityAnalyzer()

In [ ]:
df['scores'] = df['post'].apply(lambda Text: sid.polarity_scores(Text))
df.head()

,Name,Time,Post,post,scores
0,CGTN,China state-controlled media,A new Perspective in Science discusses the neu...,new perspect scienc discuss neurolog symptom a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
1,CGTN,China state-controlled media,Millions of high-risk Americans are dealing wi...,million high risk american deal strain grief n...,"{'neg': 0.217, 'neu': 0.7, 'pos': 0.083, 'comp..."
2,CGTN,China state-controlled media,"করোনায় মৃত্যু বেড়ে ৩৪, বাড়ল শনাক্তও #covid19 #...",translationprothomalo com visit covid 19 infor...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
3,"See all public posts for ""covid-19""",9 February at 20:20,Judy Ann Santos is extremely elated that her s...,judi ann santo extrem elat six year old daught...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4,Science,China state-controlled media,Feel like you're juggling more work than ever?...,feel like juggl work ever not alon two third w...,"{'neg': 0.0, 'neu': 0.946, 'pos': 0.054, 'comp..."

In [ ]:
 df = df[['Post','scores']]

In [ ]:
df

,Post,scores
0,A new Perspective in Science discusses the neu...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
1,Millions of high-risk Americans are dealing wi...,"{'neg': 0.217, 'neu': 0.7, 'pos': 0.083, 'comp..."
2,"করোনায় মৃত্যু বেড়ে ৩৪, বাড়ল শনাক্তও #covid19 #...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
3,Judy Ann Santos is extremely elated that her s...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4,Feel like you're juggling more work than ever?...,"{'neg': 0.0, 'neu': 0.946, 'pos': 0.054, 'comp..."
5,It’s simple: Eight months after your second sh...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
6,I’m instructing the Department of Labor to req...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
7,Metro Manila will retain current restrictions ...,"{'neg': 0.066, 'neu': 0.715, 'pos': 0.218, 'co..."
8,"Good news, folks: You can get free COVID-19 te...","{'neg': 0.0, 'neu': 0.754, 'pos': 0.246, 'comp..."
9,"Folks, the Delta variant — a highly infectious...","{'neg': 0.024, 'neu': 0.752, 'pos': 0.224, 'co..."
10,"In case you missed it, #TheMarkSteynShow repla...","{'neg': 0.032, 'neu': 0.968, 'pos': 0.0, 'comp..."
11,"""Our expectation is that the acute phase of th...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
12,Tune in as I deliver an update on my Administr...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
13,"If you haven’t yet, please get vaccinated. It’...","{'neg': 0.08, 'neu': 0.656, 'pos': 0.265, 'com..."
14,We’ve made incredible progress in the fight ag...,"{'neg': 0.071, 'neu': 0.852, 'pos': 0.077, 'co..."
15,"More than 2,600 Americans are dying from Covid...","{'neg': 0.249, 'neu': 0.751, 'pos': 0.0, 'comp..."
16,COVID-19 deaths are down by 90% since we took ...,"{'neg': 0.088, 'neu': 0.854, 'pos': 0.058, 'co..."
17,We have administered over one million COVID-19...,"{'neg': 0.073, 'neu': 0.896, 'pos': 0.031, 'co..."
18,The conspiracy theory that athletes are collap...,"{'neg': 0.315, 'neu': 0.685, 'pos': 0.0, 'comp..."
19,Yesterday I announced that the U.S. will donat...,"{'neg': 0.074, 'neu': 0.86, 'pos': 0.066, 'com..."
20,"Ivermectin, an anti-parasitic drug commonly us...","{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp..."
21,"Ivermectin, an anti-parasitic drug commonly us...","{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp..."
22,"Ivermectin, an anti-parasitic drug commonly us...","{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp..."
23,Hate has no place in America – and I look forw...,"{'neg': 0.369, 'neu': 0.542, 'pos': 0.088, 'co..."
24,Tune in as I join the White House COVID-19 Res...,"{'neg': 0.0, 'neu': 0.919, 'pos': 0.081, 'comp..."
25,Brazil has suffered 13% of the world's Covid-1...,"{'neg': 0.365, 'neu': 0.635, 'pos': 0.0, 'comp..."
26,I know folks have a lot of questions about COV...,"{'neg': 0.0, 'neu': 0.947, 'pos': 0.053, 'comp..."
27,"Today, on the National Day of Prayer, I reflec...","{'neg': 0.0, 'neu': 0.679, 'pos': 0.321, 'comp..."
28,We’ve made enormous progress when it comes to ...,"{'neg': 0.0, 'neu': 0.864, 'pos': 0.136, 'comp..."
29,Madhya Pradesh Chief Minister Shivraj Singh Ch...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
30,We’ve made incredible progress in the fight ag...,"{'neg': 0.062, 'neu': 0.667, 'pos': 0.271, 'co..."
31,Because of the extraordinary progress we’ve ma...,"{'neg': 0.068, 'neu': 0.859, 'pos': 0.073, 'co..."
32,Parents: kids 12 and up can now get the Pfizer...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
33,"In India, people are dying while waiting to se...","{'neg': 0.281, 'neu': 0.719, 'pos': 0.0, 'comp..."
34,"This morning, I signed the SAVE LIVES Act into...","{'neg': 0.0, 'neu': 0.791, 'pos': 0.209, 'comp..."
35,"On Friday, I sat down with my COVID-19 team fo...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
36,Tune in as I give an update on our progress to...,"{'neg': 0.078, 'neu': 0.838, 'pos': 0.084, 'co..."
37,A U.S. trial found AstraZeneca’s Covid-19 vacc...,"{'neg': 0.203, 'neu': 0.743, 'pos': 0.054, 'co..."

In [ ]:
df = pd.concat([df, df['scores'].apply(pd.Series)], axis=1)

In [ ]:
df = df[['Post','neg', 'neu', 'pos', 'compound']]

In [ ]:
df

,Post,neg,neu,pos,compound
0,A new Perspective in Science discusses the neu...,0.000,1.000,0.000,0.0000
1,Millions of high-risk Americans are dealing wi...,0.217,0.700,0.083,-0.4588
2,"করোনায় মৃত্যু বেড়ে ৩৪, বাড়ল শনাক্তও #covid19 #...",0.000,1.000,0.000,0.0000
3,Judy Ann Santos is extremely elated that her s...,0.000,1.000,0.000,0.0000
4,Feel like you're juggling more work than ever?...,0.000,0.946,0.054,0.3612
5,It’s simple: Eight months after your second sh...,0.000,1.000,0.000,0.0000
6,I’m instructing the Department of Labor to req...,0.000,1.000,0.000,0.0000
7,Metro Manila will retain current restrictions ...,0.066,0.715,0.218,0.8360
8,"Good news, folks: You can get free COVID-19 te...",0.000,0.754,0.246,0.7351
9,"Folks, the Delta variant — a highly infectious...",0.024,0.752,0.224,0.8957
10,"In case you missed it, #TheMarkSteynShow repla...",0.032,0.968,0.000,-0.1531
11,"""Our expectation is that the acute phase of th...",0.000,1.000,0.000,0.0000
12,Tune in as I deliver an update on my Administr...,0.000,1.000,0.000,0.0000
13,"If you haven’t yet, please get vaccinated. It’...",0.080,0.656,0.265,0.8360
14,We’ve made incredible progress in the fight ag...,0.071,0.852,0.077,0.0516
15,"More than 2,600 Americans are dying from Covid...",0.249,0.751,0.000,-0.7430
16,COVID-19 deaths are down by 90% since we took ...,0.088,0.854,0.058,-0.3182
17,We have administered over one million COVID-19...,0.073,0.896,0.031,-0.4019
18,The conspiracy theory that athletes are collap...,0.315,0.685,0.000,-0.8316
19,Yesterday I announced that the U.S. will donat...,0.074,0.860,0.066,-0.0772
20,"Ivermectin, an anti-parasitic drug commonly us...",0.302,0.698,0.000,-0.5621
21,"Ivermectin, an anti-parasitic drug commonly us...",0.302,0.698,0.000,-0.5621
22,"Ivermectin, an anti-parasitic drug commonly us...",0.302,0.698,0.000,-0.5621
23,Hate has no place in America – and I look forw...,0.369,0.542,0.088,-0.8519
24,Tune in as I join the White House COVID-19 Res...,0.000,0.919,0.081,0.2960
25,Brazil has suffered 13% of the world's Covid-1...,0.365,0.635,0.000,-0.8979
26,I know folks have a lot of questions about COV...,0.000,0.947,0.053,0.2023
27,"Today, on the National Day of Prayer, I reflec...",0.000,0.679,0.321,0.9136
28,We’ve made enormous progress when it comes to ...,0.000,0.864,0.136,0.7184
29,Madhya Pradesh Chief Minister Shivraj Singh Ch...,0.000,1.000,0.000,0.0000
30,We’ve made incredible progress in the fight ag...,0.062,0.667,0.271,0.8316
31,Because of the extraordinary progress we’ve ma...,0.068,0.859,0.073,0.0516
32,Parents: kids 12 and up can now get the Pfizer...,0.000,1.000,0.000,0.0000
33,"In India, people are dying while waiting to se...",0.281,0.719,0.000,-0.8316
34,"This morning, I signed the SAVE LIVES Act into...",0.000,0.791,0.209,0.7506
35,"On Friday, I sat down with my COVID-19 team fo...",0.000,1.000,0.000,0.0000
36,Tune in as I give an update on our progress to...,0.078,0.838,0.084,0.0516
37,A U.S. trial found AstraZeneca’s Covid-19 vacc...,0.203,0.743,0.054,-0.6124

YouTube

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/youtube.csv')

In [ ]:
df.columns

Index(['Title', 'Description', 'Duration', 'Views', 'Channel', 'Uploaded'], dtype='object')

In [ ]:
df.shape

(4, 6)

In [ ]:
df.head()

                                               Title  ...      Uploaded
0  COVID-19: Hong Kong reports more than 4,200 ne...  ...    3 days ago
1  States Across US Prepare To End Mask Mandates ...  ...  13 hours ago
2  Singapore to streamline COVID-19 and border ru...  ...    3 days ago
3  We need to rethink Covid-19 restrictions as ca...  ...     1 day ago

[4 rows x 6 columns]

In [ ]:
import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
corpus=[]

for i in range(0, 4):
  title = re.sub('(@[A-Za-z0-9]+)|(#[A-Za-z0-9]+)|([^0-9A-Za-z t])|(w+://S+)', ' ', df['Title'][i])
  title = title.split("https")[0]
  title = title.lower()
  title = title.split()
  title = [ps.stem(word) for word in title if not word in set(all_stopwords)]
  title = ' '.join(title)
  corpus.append(title)

In [ ]:
df['title'] = corpus
df.head()

                                               Title  ...                                              title
0  COVID-19: Hong Kong reports more than 4,200 ne...  ...           covid 19 hong kong report 4 200 new case
1  States Across US Prepare To End Mask Mandates ...  ...  state across us prepar end mask mandat covid 1...
2  Singapore to streamline COVID-19 and border ru...  ...  singapor streamlin covid 19 border rule announ...
3  We need to rethink Covid-19 restrictions as ca...  ...  need rethink covid 19 restrict case number dro...

[4 rows x 7 columns]

In [ ]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [ ]:
sid = SentimentIntensityAnalyzer()

In [ ]:
df['scores'] = df['title'].apply(lambda Text: sid.polarity_scores(Text))
df.head()

                                               Title  ...                                             scores
0  COVID-19: Hong Kong reports more than 4,200 ne...  ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
1  States Across US Prepare To End Mask Mandates ...  ...  {'neg': 0.16, 'neu': 0.84, 'pos': 0.0, 'compou...
2  Singapore to streamline COVID-19 and border ru...  ...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
3  We need to rethink Covid-19 restrictions as ca...  ...  {'neg': 0.313, 'neu': 0.6, 'pos': 0.087, 'comp...

[4 rows x 8 columns]

In [ ]:
 df[['Title','scores']]

                                               Title                                             scores
0  COVID-19: Hong Kong reports more than 4,200 ne...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
1  States Across US Prepare To End Mask Mandates ...  {'neg': 0.16, 'neu': 0.84, 'pos': 0.0, 'compou...
2  Singapore to streamline COVID-19 and border ru...  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
3  We need to rethink Covid-19 restrictions as ca...  {'neg': 0.313, 'neu': 0.6, 'pos': 0.087, 'comp...

In [ ]:
df = pd.concat([df, df['scores'].apply(pd.Series)], axis=1)

In [ ]:
df_y = df[['Title','neg', 'neu', 'pos', 'compound']]

In [ ]:
df_y

                                               Title    neg  ...    pos  compound
0  COVID-19: Hong Kong reports more than 4,200 ne...  0.000  ...  0.000    0.0000
1  States Across US Prepare To End Mask Mandates ...  0.160  ...  0.000   -0.2732
2  Singapore to streamline COVID-19 and border ru...  0.000  ...  0.000    0.0000
3  We need to rethink Covid-19 restrictions as ca...  0.313  ...  0.087   -0.5267

[4 rows x 5 columns]